"""Unified display extension framework for HoloViews.

This module provides a single, consistent mechanism for injecting
auxiliary display content into all rendering paths:

- Notebook HTML repr  (``_repr_html_`` / IPython display hooks)
- Hover tooltips      (Bokeh HoverTool, matplotlib format_coord, Plotly hovertemplate)
- Side info panels    (Bokeh sidebar/extra panels, Panel layouts)
- Python repr         (``__repr__`` / PrettyPrinter)
- Generic metadata    (carried through all channels above)

Previously these concerns were addressed ad-hoc in
``ipython/display_hooks.py``, ``plotting/renderer.py``, each backend's
``element.py`` and the core ``Dimensioned`` class.  The extension
registry defined below centralises them so that any piece of extra
information (DynamicMap operation info, operation debug output, user
metadata, ...) only has to be registered once to appear consistently
everywhere the object is rendered.

Typical usage::

    from holoviews.core.display_extension import (
        DisplayExtension, register_extension, apply_extensions
    )

    class MyExtension(DisplayExtension):
        name = "my_ext"

        def get_hover_fields(self, obj):
            return ["custom_field"]

        def get_html_panel(self, obj):
            return "<div>Custom info</div>"

    register_extension(MyExtension())

    # Internally, rendering code consumes extensions via:
    panels = apply_extensions(obj, "html_panel")   # list of HTML strings
    fields = apply_extensions(obj, "hover_fields") # aggregated field list

See the docstring of :class:`DisplayExtension` for the full set of
hooks a subclass may override.
"""

from __future__ import annotations

import enum
import html
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple, Union


__all__ = [
    "DisplayContext",
    "DisplayExtension",
    "DisplayExtensionRegistry",
    "DisplayPayload",
    "HoverSpec",
    "PanelSpec",
    "register_extension",
    "unregister_extension",
    "get_registry",
    "apply_extensions",
    "get_hover_fields",
    "get_hover_data",
    "get_hover_tooltips",
    "get_html_panels",
    "get_side_panels",
    "get_text_extras",
    "get_metadata",
    "get_display_payload",
    "DimensionedHoverExtension",
    "DynamicMapExtension",
    "OperationContextExtension",
    "MetadataExtension",
]


# ---------------------------------------------------------------------------
# Helpers / data containers
# ---------------------------------------------------------------------------


class DisplayContext(enum.Flag):
    """Display contexts in which an extension may contribute content."""

    NONE = 0
    HOVER_TOOLTIP = enum.auto()
    HTML_REPR = enum.auto()
    SIDE_PANEL = enum.auto()
    TEXT_REPR = enum.auto()
    METADATA = enum.auto()
    ALL = HOVER_TOOLTIP | HTML_REPR | SIDE_PANEL | TEXT_REPR | METADATA


@dataclass
class HoverSpec:
    """Normalised specification of a single hover/tooltip entry.

    A list of these is produced by :meth:`DisplayExtension.get_hover_specs`
    and consumed by the backends when building tooltip widgets.
    """

    name: str
    label: Optional[str] = None
    formatter: Optional[Union[str, Callable[[Any], str]]] = None
    values: Optional[Any] = None
    enabled: bool = True


@dataclass
class PanelSpec:
    """Normalised specification of an auxiliary information panel.

    Produced by :meth:`DisplayExtension.get_panel_specs` and used to
    render side panels (in Bokeh / Panel) or inline HTML blocks
    (notebook repr).
    """

    title: Optional[str] = None
    content: Optional[Any] = None
    html_content: Optional[str] = None
    position: str = "right"
    priority: int = 0
    extra: Dict[str, Any] = field(default_factory=dict)
    enabled: bool = True


@dataclass
class DisplayPayload:
    """Unified container for all display-related content generated by
    the extension registry.

    A single :class:`DisplayPayload` is produced from an object by
    :func:`get_display_payload` and consumed by the renderer, display
    hooks, and backends.  This ensures that the same aggregated
    information is used for hover tooltips, HTML repr, side panels,
    text repr and metadata everywhere the object is rendered.
    """

    hover_specs: List[HoverSpec] = field(default_factory=list)
    hover_data: Dict[str, Any] = field(default_factory=dict)
    hover_tooltips: List[Tuple[str, str]] = field(default_factory=list)
    panel_specs: List[PanelSpec] = field(default_factory=list)
    html_panels: List[str] = field(default_factory=list)
    side_panels: List[PanelSpec] = field(default_factory=list)
    text_extras: List[Tuple[str, Any]] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    source_obj: Optional[Any] = None

    @property
    def has_hover(self) -> bool:
        return bool(self.hover_specs)

    @property
    def has_panels(self) -> bool:
        return bool(self.html_panels)

    @property
    def has_text_extras(self) -> bool:
        return bool(self.text_extras)

    @property
    def has_metadata(self) -> bool:
        return bool(self.metadata)

    @property
    def has_any(self) -> bool:
        return self.has_hover or self.has_panels or self.has_text_extras or self.has_metadata

    def as_text_suffix(self) -> str:
        """Return a string suffix suitable for appending to ``__repr__``."""
        if not self.text_extras:
            return ""
        lines = []
        for label, value in self.text_extras:
            lines.append(f"   |_{label}: {value!r}")
        return "\n" + "\n".join(lines)

    def wrap_html(self, main_html: str) -> str:
        """Wrap *main_html* with side panels in a flex layout."""
        if not self.html_panels:
            return main_html
        panels_html = "".join(self.html_panels)
        return (
            '<div class="hv-display-wrapper" style="display:flex;flex-wrap:wrap;'
            'align-items:flex-start;gap:12px;">'
            '<div class="hv-main-plot" style="flex:1 1 auto;min-width:0;">'
            + main_html
            + "</div>"
            + '<div class="hv-side-panels" style="flex:0 1 320px;max-width:100%;">'
            + panels_html
            + "</div>"
            + "</div>"
        )

    def update_mime_metadata(self, metadata: Dict[str, Any], mime_key: str) -> None:
        """Update a MIME metadata dict in-place with this payload's metadata."""
        if not self.metadata:
            return
        hv_exec_meta = metadata.setdefault(mime_key, {})
        hv_exec_meta["hv_metadata"] = dict(self.metadata)


# ---------------------------------------------------------------------------
# Extension base class
# ---------------------------------------------------------------------------


class DisplayExtension:
    """Base class for display extensions.

    Subclasses override *one or more* of the hook methods below.  Each
    hook receives the HoloViews object being rendered and returns
    extension data appropriate to that hook.  Hooks are always called
    with an object; if the extension does not apply to that object it
    should return ``None`` (or an empty collection) so the registry
    moves on to the next extension.

    Hook return contracts:

    * :meth:`get_hover_specs`  →  ``list[HoverSpec]`` or ``None``
    * :meth:`get_hover_fields` →  ``list[str | Dimension | dim()]`` or ``None``
      (convenience; the registry will translate these into HoverSpecs)
    * :meth:`get_panel_specs`  →  ``list[PanelSpec]`` or ``None``
    * :meth:`get_html_panel`   →  ``str`` HTML block (convenience)
    * :meth:`get_text_extras`  →  ``list[(label, value)]`` tuples appended to repr
    * :meth:`get_metadata`     →  ``dict`` of JSON-serialisable metadata

    In addition, :meth:`applies_to` lets subclasses short-circuit for
    unsupported object types (the default is to apply to any object).
    """

    name: str = "unnamed_extension"
    priority: int = 100
    enabled: bool = True
    contexts: DisplayContext = DisplayContext.ALL

    # ------------------------------------------------------------------ hooks

    def applies_to(self, obj: Any) -> bool:
        """Return True if this extension knows how to extend *obj*."""
        return True

    # -- Hover / tooltip --------------------------------------------------

    def get_hover_fields(self, obj: Any) -> Optional[List[Any]]:
        """Return a list of hover field specs (strings, Dimension, dim()).

        This is a convenience entry point.  Extensions that need fine
        control (custom labels, per-field formatters, pre-computed value
        arrays) should override :meth:`get_hover_specs` instead.
        """
        return None

    def get_hover_specs(self, obj: Any) -> Optional[List[HoverSpec]]:
        """Return the canonical list of HoverSpec objects for *obj*.

        The default implementation turns the output of
        :meth:`get_hover_fields` into HoverSpecs; subclasses should
        override this directly if they already have richer information.
        """
        fields = self.get_hover_fields(obj)
        if not fields:
            return None
        specs: List[HoverSpec] = []
        for f in fields:
            name = self._field_name(f, obj)
            specs.append(HoverSpec(name=name))
        return specs

    # -- Panels (side panel / HTML repr) ----------------------------------

    def get_html_panel(self, obj: Any) -> Optional[str]:
        """Return a raw HTML string to include inline next to the plot.

        Convenience alternative to :meth:`get_panel_specs`.
        """
        return None

    def get_panel_specs(self, obj: Any) -> Optional[List[PanelSpec]]:
        """Return the canonical list of PanelSpec objects for *obj*."""
        html_panel = self.get_html_panel(obj)
        if html_panel is None:
            return None
        return [PanelSpec(html_content=html_panel, title=self.name)]

    # -- Text repr --------------------------------------------------------

    def get_text_extras(self, obj: Any) -> Optional[List[Tuple[str, Any]]]:
        """Return ``[(label, value)]`` tuples to append to the text repr."""
        return None

    # -- Metadata ---------------------------------------------------------

    def get_metadata(self, obj: Any) -> Optional[Dict[str, Any]]:
        """Return a JSON-serialisable dict of extra metadata."""
        return None

    # ------------------------------------------------------------------ utils

    @staticmethod
    def _field_name(field: Any, obj: Any) -> str:
        from .dimension import Dimension
        from ..util.transform import dim as _dim

        if isinstance(field, _dim):
            if len(field.ops) == 0:
                return DisplayExtension._field_name(field.dimension, obj)
            return str(field)
        if isinstance(field, Dimension):
            return field.name
        if isinstance(field, str):
            return field
        return str(field)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


class DisplayExtensionRegistry:
    """Ordered registry of :class:`DisplayExtension` instances.

    The registry owns the :func:`apply_extensions` helper used by the
    rest of HoloViews to collect extension contributions.  Extensions
    are kept in insertion order (subject to ``priority``) and may be
    enabled / disabled at runtime.

    There is one process-wide registry returned by :func:`get_registry`.
    """

    def __init__(self) -> None:
        self._extensions: "OrderedDict[str, DisplayExtension]" = OrderedDict()
        self._register_defaults()

    # ------------------------------------------------------------------ API

    def register(self, extension: DisplayExtension) -> None:
        """Register an extension (replaces any previous with same name)."""
        if not isinstance(extension, DisplayExtension):
            raise TypeError(
                f"Expected DisplayExtension instance, got {type(extension).__name__}"
            )
        self._extensions[extension.name] = extension
        self._sort()

    def unregister(self, name: str) -> Optional[DisplayExtension]:
        return self._extensions.pop(name, None)

    def get(self, name: str) -> Optional[DisplayExtension]:
        return self._extensions.get(name)

    def list(self) -> List[DisplayExtension]:
        return list(self._extensions.values())

    def clear(self) -> None:
        self._extensions.clear()
        self._register_defaults()

    # ------------------------------------------------------------ aggregation

    def apply(
        self,
        obj: Any,
        hook: str,
        context: DisplayContext = DisplayContext.ALL,
    ) -> List[Any]:
        """Run *hook* on every applicable enabled extension.

        Returns a flat list of the non-``None`` results.

        Parameters
        ----------
        obj:
            The HoloViews object being rendered.
        hook:
            Name of a method on :class:`DisplayExtension`, e.g.
            ``"get_hover_specs"``, ``"get_metadata"``.
        context:
            Only extensions whose ``contexts`` flag intersects this
            value are called.
        """
        results: List[Any] = []
        for ext in self._extensions.values():
            if not ext.enabled:
                continue
            if not (ext.contexts & context):
                continue
            if not ext.applies_to(obj):
                continue
            method = getattr(ext, hook, None)
            if method is None:
                continue
            try:
                result = method(obj)
            except Exception:  # noqa: BLE001 - never let a bad extension break rendering
                result = None
            if result is None:
                continue
            if isinstance(result, list):
                results.extend(result)
            else:
                results.append(result)
        return results

    # ------------------------------------------------------------------ utils

    def _register_defaults(self) -> None:
        self._extensions[DimensionedHoverExtension.name] = DimensionedHoverExtension()
        self._extensions[DynamicMapExtension.name] = DynamicMapExtension()
        self._extensions[OperationContextExtension.name] = OperationContextExtension()
        self._extensions[MetadataExtension.name] = MetadataExtension()
        self._sort()

    def _sort(self) -> None:
        self._extensions = OrderedDict(
            sorted(self._extensions.items(), key=lambda kv: (-kv[1].priority, kv[0]))
        )


# ---------------------------------------------------------------------------
# Module-level convenience API
# ---------------------------------------------------------------------------


_global_registry: Optional[DisplayExtensionRegistry] = None


def get_registry() -> DisplayExtensionRegistry:
    """Return the process-wide :class:`DisplayExtensionRegistry`."""
    global _global_registry
    if _global_registry is None:
        _global_registry = DisplayExtensionRegistry()
    return _global_registry


def register_extension(extension: DisplayExtension) -> None:
    get_registry().register(extension)


def unregister_extension(name: str) -> Optional[DisplayExtension]:
    return get_registry().unregister(name)


def apply_extensions(obj: Any, hook: str, context: DisplayContext = DisplayContext.ALL) -> List[Any]:
    return get_registry().apply(obj, hook, context)


# ----------------------------------------------------------- specialised getters


def get_hover_fields(obj: Any) -> List[HoverSpec]:
    """Aggregate HoverSpecs from every extension that applies to *obj*.

    This is the single entry point used by the backends when building
    hover tooltips.  It is the successor to the ad-hoc
    ``element._get_hover_fields`` / ``plot._hover_opts`` combination.
    """
    specs = apply_extensions(obj, "get_hover_specs", DisplayContext.HOVER_TOOLTIP)
    dedup: "OrderedDict[str, HoverSpec]" = OrderedDict()
    for spec in specs:
        if not isinstance(spec, HoverSpec):
            continue
        if not spec.enabled:
            continue
        if spec.name in dedup and spec.label:
            dedup[spec.name].label = spec.label or dedup[spec.name].label
            dedup[spec.name].formatter = spec.formatter or dedup[spec.name].formatter
            dedup[spec.name].values = spec.values if spec.values is not None else dedup[spec.name].values
        else:
            dedup[spec.name] = spec
    return list(dedup.values())


def get_hover_field_names(obj: Any) -> List[str]:
    return [s.name for s in get_hover_fields(obj)]


def get_hover_data(obj: Any) -> Dict[str, Any]:
    """Return the aggregated ``{field_name: values}`` dict for *obj*.

    Falls back to pulling values directly from the element when an
    extension declared a HoverSpec without a ``values`` array.
    """
    data: Dict[str, Any] = {}
    from . import util
    from .dimension import Dimensioned

    is_dim = isinstance(obj, Dimensioned)
    for spec in get_hover_fields(obj):
        if spec.values is not None:
            data[util.dimension_sanitizer(spec.name)] = spec.values
            continue
        if not is_dim:
            continue
        try:
            dim = obj.get_dimension(spec.name)
            if dim is not None:
                data[util.dimension_sanitizer(spec.name)] = obj.dimension_values(dim)
            else:
                from ..util.transform import dim as _dim
                data[util.dimension_sanitizer(spec.name)] = _dim(spec.name).apply(obj)
        except (KeyError, ValueError):
            pass
    return data


def get_hover_tooltips(obj: Any) -> List[Tuple[str, str]]:
    """Return a list of ``(label, value_ref)`` tuples suitable for use
    directly as Bokeh ``tooltips`` or as the basis for other backends.
    """
    from . import util

    tooltips: List[Tuple[str, str]] = []
    for spec in get_hover_fields(obj):
        label = spec.label or spec.name
        safe = util.dimension_sanitizer(spec.name)
        tooltips.append((label, f"@{{{safe}}}"))
    return tooltips


def get_panel_specs(obj: Any, position: Optional[str] = None) -> List[PanelSpec]:
    specs = apply_extensions(obj, "get_panel_specs", DisplayContext.SIDE_PANEL | DisplayContext.HTML_REPR)
    result = []
    for spec in specs:
        if not isinstance(spec, PanelSpec):
            continue
        if not spec.enabled:
            continue
        if position is not None and spec.position != position:
            continue
        result.append(spec)
    result.sort(key=lambda s: -s.priority)
    return result


def get_html_panels(obj: Any) -> List[str]:
    """Return all HTML panels as a list of strings, in priority order."""
    panels: List[str] = []
    for spec in get_panel_specs(obj):
        if spec.html_content:
            panels.append(spec.html_content)
        elif spec.content is not None:
            try:
                panels.append(html.escape(str(spec.content)))
            except Exception:  # noqa: BLE001
                pass
    return panels


def get_side_panels(obj: Any, position: str = "right") -> List[PanelSpec]:
    return get_panel_specs(obj, position=position)


def get_text_extras(obj: Any) -> List[Tuple[str, Any]]:
    """Aggregate text extras from all extensions for *obj*.

    Each extension may return a list of ``(label, value)`` tuples,
    which are flattened by :meth:`DisplayExtensionRegistry.apply`
    before being returned here.
    """
    extras: List[Tuple[str, Any]] = []
    for item in apply_extensions(obj, "get_text_extras", DisplayContext.TEXT_REPR):
        extras.append(item)
    return extras


def get_metadata(obj: Any) -> Dict[str, Any]:
    meta: Dict[str, Any] = {}
    for batch in apply_extensions(obj, "get_metadata", DisplayContext.METADATA):
        if isinstance(batch, dict):
            meta.update(batch)
    return meta


def get_display_payload(obj: Any) -> DisplayPayload:
    """Build a single :class:`DisplayPayload` containing every piece of
    display-extension content for *obj*.

    This is the primary entry point used by the renderer and display
    hooks.  It calls each getter once and stores the aggregated
    results, ensuring all rendering paths consume the exact same data.

    Parameters
    ----------
    obj:
        The HoloViews object being rendered.

    Returns
    -------
    DisplayPayload
        Populated with hover specs/data, panels, text extras and
        metadata aggregated from every registered extension.
    """
    return DisplayPayload(
        hover_specs=get_hover_fields(obj),
        hover_data=get_hover_data(obj),
        hover_tooltips=get_hover_tooltips(obj),
        panel_specs=get_panel_specs(obj),
        html_panels=get_html_panels(obj),
        side_panels=get_side_panels(obj),
        text_extras=get_text_extras(obj),
        metadata=get_metadata(obj),
        source_obj=obj,
    )


# ---------------------------------------------------------------------------
# Built-in extensions
# ---------------------------------------------------------------------------


class DimensionedHoverExtension(DisplayExtension):
    """Supplies hover fields from the ``hover_fields`` / ``hover_formatters`` /
    ``hover_aliases`` parameters declared on :class:`Dimensioned`.

    This is a direct lift of the logic previously encoded in the
    private ``Dimensioned._get_hover_*`` helpers; moving it into an
    extension means that same configuration now also participates in
    the side-panel and text-repr channels automatically.
    """

    name = "dimensioned_hover"
    priority = 1000
    contexts = DisplayContext.HOVER_TOOLTIP | DisplayContext.TEXT_REPR | DisplayContext.METADATA

    def applies_to(self, obj: Any) -> bool:
        from .dimension import Dimensioned
        return isinstance(obj, Dimensioned)

    def get_hover_specs(self, obj: Any) -> Optional[List[HoverSpec]]:
        from .dimension import Dimension
        from ..util.transform import dim as _dim

        fields = obj.hover_fields
        if fields is None:
            fields = list(obj.kdims) + list(obj.vdims)

        specs: List[HoverSpec] = []
        for f in fields:
            if isinstance(f, (str, Dimension)):
                existing_dim = obj.get_dimension(f)
                field_obj = existing_dim if existing_dim is not None else f
            else:
                field_obj = f

            field_name = obj._resolve_hover_field_name(field_obj)
            label = obj._get_hover_field_label(field_obj)
            formatter = obj._get_hover_formatter(field_obj)

            values = None
            try:
                if isinstance(field_obj, _dim):
                    values = field_obj.apply(obj)
                elif isinstance(field_obj, Dimension):
                    values = obj.dimension_values(field_obj)
                else:
                    dim = obj.get_dimension(field_name)
                    if dim is not None:
                        values = obj.dimension_values(dim)
            except (KeyError, ValueError):
                pass

            specs.append(
                HoverSpec(
                    name=field_name,
                    label=label,
                    formatter=formatter,
                    values=values,
                )
            )
        return specs

    def get_text_extras(self, obj: Any) -> Optional[List[Tuple[str, Any]]]:
        if obj.hover_fields is None:
            return None
        return [("hover_fields", [s.name for s in self.get_hover_specs(obj) or []])]

    def get_metadata(self, obj: Any) -> Optional[Dict[str, Any]]:
        if obj.hover_fields is None:
            return None
        return {
            "hover_fields": [s.name for s in self.get_hover_specs(obj) or []],
            "hover_aliases": dict(obj.hover_aliases),
        }


class DynamicMapExtension(DisplayExtension):
    """Exposes DynamicMap runtime state: callback, streams (with their
    current parameter values), cache utilisation, unbounded dimensions,
    and the underlying operation when the DynamicMap wraps an
    :class:`~holoviews.core.operation.Operation`.

    All information is drawn from the live DynamicMap object so that
    the side panel, text repr and metadata always reflect the current
    state at render time.
    """

    name = "dynamicmap"
    priority = 500
    contexts = DisplayContext.ALL

    def applies_to(self, obj: Any) -> bool:
        from .spaces import DynamicMap
        return isinstance(obj, DynamicMap)

    def _collect_runtime_state(self, obj: Any) -> Dict[str, Any]:
        """Harvest live runtime information from a DynamicMap instance."""
        state: Dict[str, Any] = {}

        callback = getattr(obj, "callback", None)
        if callback is not None:
            op = getattr(callback, "operation", None)
            if op is not None:
                state["operation"] = getattr(op, "__name__", str(op))
                try:
                    from .operation import Operation
                    if isinstance(op, Operation):
                        op_params = {
                            k: v for k, v in op.param.values().items()
                            if k not in ("name",)
                        }
                        if op_params:
                            state["operation_params"] = op_params
                        state["operation_type"] = type(op).__name__
                except Exception:  # noqa: BLE001
                    pass
            state["callback"] = getattr(callback, "__name__", type(callback).__name__)
            if hasattr(callback, "callable"):
                inner = callback.callable
                state["callback"] = getattr(inner, "__name__", str(inner))

        stream_info: List[Dict[str, Any]] = []
        for s in obj.streams:
            info: Dict[str, Any] = {"type": type(s).__name__}
            try:
                params = s.param.objects("existing")
                vals = {k: v for k, v in params.items() if k != "name"}
                if vals:
                    info["parameters"] = vals
            except Exception:  # noqa: BLE001
                pass
            stream_info.append(info)
        state["streams"] = stream_info
        state["stream_count"] = len(obj.streams)

        try:
            cache_used = len(obj.data)
            state["cache_used"] = cache_used
            state["cache_capacity"] = obj.cache_size
            if obj.cache_size > 0:
                state["cache_fill_pct"] = round(100 * cache_used / obj.cache_size, 1)
        except Exception:  # noqa: BLE001
            pass

        unbounded = obj.unbounded
        if unbounded:
            state["unbounded_dims"] = unbounded

        positional = getattr(obj, "positional_stream_args", False)
        if positional:
            state["positional_stream_args"] = True

        return state

    def get_text_extras(self, obj: Any) -> Optional[List[Tuple[str, Any]]]:
        state = self._collect_runtime_state(obj)
        extras: List[Tuple[str, Any]] = []
        if "operation" in state:
            extras.append(("operation", state["operation"]))
        extras.append(("streams", state.get("stream_count", 0)))
        if "cache_used" in state:
            extras.append(("cache", f"{state['cache_used']}/{state.get('cache_capacity', '?')}"))
        if "unbounded_dims" in state:
            extras.append(("unbounded", state["unbounded_dims"]))
        return extras

    def get_metadata(self, obj: Any) -> Optional[Dict[str, Any]]:
        return self._collect_runtime_state(obj)

    def get_html_panel(self, obj: Any) -> Optional[str]:
        state = self._collect_runtime_state(obj)
        if not state:
            return None

        sections: List[str] = []

        if "operation" in state:
            op_type = state.get("operation_type", "")
            label = f"{state['operation']} ({op_type})" if op_type else state["operation"]
            sections.append(
                f'<div style="margin-bottom:6px;">'
                f'<span style="font-weight:bold;color:#4a6b00;">Operation:</span> '
                f'{html.escape(label)}</div>'
            )
            if "operation_params" in state:
                param_rows = "".join(
                    f'<tr><td style="padding:1px 8px 1px 0;color:#666;">{html.escape(str(k))}</td>'
                    f'<td style="padding:1px 0;">{html.escape(str(v))}</td></tr>'
                    for k, v in state["operation_params"].items()
                )
                sections.append(
                    f'<div style="margin-left:12px;margin-bottom:4px;">'
                    f'<table style="border-collapse:collapse;font-size:11px;">{param_rows}</table></div>'
                )

        stream_rows = ""
        for s in state.get("streams", []):
            param_count = len(s.get("parameters", {}))
            stream_rows += (
                f'<tr><td style="padding:1px 0;">{html.escape(s["type"])}'
                f'<span style="color:#999;"> ({param_count} params)</span></td></tr>'
            )
        if stream_rows:
            sections.append(
                f'<div style="margin-bottom:6px;">'
                f'<span style="font-weight:bold;color:#4a6b00;">Streams ({state.get("stream_count", 0)}):</span></div>'
                f'<div style="margin-left:12px;">'
                f'<table style="border-collapse:collapse;font-size:11px;">{stream_rows}</table></div>'
            )

        cache_used = state.get("cache_used", "?")
        cache_cap = state.get("cache_capacity", "?")
        fill = state.get("cache_fill_pct")
        fill_str = f" ({fill}%)" if fill is not None else ""
        sections.append(
            f'<div><span style="font-weight:bold;color:#4a6b00;">Cache:</span> '
            f'{cache_used}/{cache_cap}{fill_str}</div>'
        )

        if "unbounded_dims" in state:
            sections.append(
                f'<div style="color:#b94a00;"><span style="font-weight:bold;">Unbounded:</span> '
                f'{html.escape(str(state["unbounded_dims"]))}</div>'
            )

        content = "".join(sections)
        return (
            f'<div class="hv-dynamicmap-panel" style="font-family:monospace;font-size:12px;'
            f'padding:8px;border-left:3px solid #76b900;background:#f7fbf2;margin-bottom:6px;">'
            f'<div style="font-weight:bold;margin-bottom:6px;color:#4a6b00;">DynamicMap Runtime</div>'
            f'{content}</div>'
        )

    def get_panel_specs(self, obj: Any) -> Optional[List[PanelSpec]]:
        html_panel = self.get_html_panel(obj)
        if html_panel is None:
            return None
        return [PanelSpec(title="DynamicMap", html_content=html_panel, position="right", priority=500)]


class MetadataExtension(DisplayExtension):
    """Surfaces any ``.metadata`` attribute set on the object.

    Users can attach arbitrary structured metadata via e.g.::

        curve.metadata = {"source": "...", "units": "m/s"}

    and this extension makes it visible in every rendering channel.
    """

    name = "metadata"
    priority = 300
    contexts = DisplayContext.ALL

    def applies_to(self, obj: Any) -> bool:
        return hasattr(obj, "metadata") and obj.metadata not in (None, {})

    def get_text_extras(self, obj: Any) -> Optional[List[Tuple[str, Any]]]:
        return [("metadata", obj.metadata)]

    def get_metadata(self, obj: Any) -> Optional[Dict[str, Any]]:
        try:
            return dict(obj.metadata)
        except Exception:  # noqa: BLE001
            return {"metadata": obj.metadata}

    def get_html_panel(self, obj: Any) -> Optional[str]:
        meta = self.get_metadata(obj) or {}
        if not meta:
            return None
        rows = "".join(
            f'<tr><td style="font-weight:bold;padding:2px 8px 2px 0;text-align:left;'
            f'vertical-align:top;color:#555;">{html.escape(str(k))}</td>'
            f'<td style="padding:2px 0;text-align:left;">{html.escape(str(v))}</td></tr>'
            for k, v in meta.items()
        )
        return (
            f'<div class="hv-metadata-panel" style="font-family:monospace;font-size:12px;'
            f'padding:8px;border-left:3px solid #0076b9;background:#f2f7fb;margin-bottom:6px;">'
            f'<div style="font-weight:bold;margin-bottom:4px;color:#003a6b;">Metadata</div>'
            f'<table style="border-collapse:collapse;">{rows}</table></div>'
        )

    def get_panel_specs(self, obj: Any) -> Optional[List[PanelSpec]]:
        html_panel = self.get_html_panel(obj)
        if html_panel is None:
            return None
        return [PanelSpec(title="Metadata", html_content=html_panel, position="right", priority=300)]


class OperationContextExtension(DisplayExtension):
    """Surfaces operation execution context for objects produced by
    rasterize / datashade / resample and other operations.

    This extension delegates to :func:`get_execution_context_meta` to
    collect metadata from several possible sources:

    * ``obj._hv_execution_context`` — an
      :class:`~holoviews.operation.resample.OperationExecutionContext`
      providing sampling parameters, bounds, precompute state, etc.
    * ``obj._operation_context`` — a free-form dict that operations
      populate with timing, parameter snapshots, and provenance.
    * ``obj.operation_pipeline`` — a list of operation steps for
      provenance chains.
    * ``obj.callback.operation`` — for DynamicMaps produced by
      ``.apply()`` / ``.map()``.

    All information is aggregated into a single display payload and is
    surfaced in HTML side panels, text reprs, notebook MIME metadata
    and programmatic access via :func:`get_metadata`.
    """

    name = "operation_context"
    priority = 400
    contexts = DisplayContext.ALL

    def applies_to(self, obj: Any) -> bool:
        from ..operation import get_execution_context_meta
        ctx = get_execution_context_meta(obj)
        has_pipeline = hasattr(obj, "operation_pipeline") and obj.operation_pipeline
        return bool(ctx) or has_pipeline

    def _collect_context(self, obj: Any) -> Dict[str, Any]:
        from ..operation import get_execution_context_meta
        ctx = dict(get_execution_context_meta(obj))

        if hasattr(obj, "operation_pipeline") and obj.operation_pipeline:
            pipeline = obj.operation_pipeline
            ctx["pipeline"] = [
                {
                    "operation": getattr(step, "__name__", type(step).__name__),
                    "type": type(step).__name__,
                }
                for step in pipeline
            ]

        return ctx

    def get_text_extras(self, obj: Any) -> Optional[List[Tuple[str, Any]]]:
        ctx = self._collect_context(obj)
        if not ctx:
            return None
        extras: List[Tuple[str, Any]] = []
        if "operation" in ctx:
            extras.append(("op", ctx["operation"]))
        if "elapsed_ms" in ctx:
            extras.append(("elapsed", f"{ctx['elapsed_ms']:.1f}ms"))
        if "width" in ctx and "height" in ctx:
            extras.append(("resolution", f"{ctx['width']}x{ctx['height']}"))
        if "pipeline" in ctx:
            extras.append(("pipeline_depth", len(ctx["pipeline"])))
        return extras

    def get_metadata(self, obj: Any) -> Optional[Dict[str, Any]]:
        ctx = self._collect_context(obj)
        return ctx if ctx else None

    def get_html_panel(self, obj: Any) -> Optional[str]:
        ctx = self._collect_context(obj)
        if not ctx:
            return None

        rows = ""
        key_order = [
            "operation", "operation_type", "width", "height", "pixel_ratio",
            "x_sampling", "y_sampling", "x_range", "y_range", "bounds",
            "expand", "xtype", "ytype", "use_precompute", "precompute",
            "elapsed_ms", "precomputed_keys",
        ]
        ordered_keys = [k for k in key_order if k in ctx]
        other_keys = [k for k in ctx if k not in key_order and k != "pipeline" and k != "operation_params"]

        for k in ordered_keys + other_keys:
            v = ctx[k]
            if k == "operation_params":
                param_rows = "".join(
                    f'<tr><td style="padding:1px 6px 1px 0;color:#666;">{html.escape(str(pk))}</td>'
                    f'<td style="padding:1px 0;">{html.escape(str(pv))}</td></tr>'
                    for pk, pv in v.items()
                )
                rows += (
                    f'<tr><td style="font-weight:bold;padding:2px 8px 2px 0;vertical-align:top;color:#555;">'
                    f'{html.escape(str(k))}</td>'
                    f'<td><table style="border-collapse:collapse;font-size:11px;">{param_rows}</table></td></tr>'
                )
            elif k == "pipeline":
                steps = ", ".join(s.get("operation", "?") for s in v)
                rows += (
                    f'<tr><td style="font-weight:bold;padding:2px 8px 2px 0;color:#555;">'
                    f'{html.escape(str(k))}</td>'
                    f'<td style="padding:2px 0;">{html.escape(steps)}</td></tr>'
                )
            else:
                rows += (
                    f'<tr><td style="font-weight:bold;padding:2px 8px 2px 0;color:#555;">'
                    f'{html.escape(str(k))}</td>'
                    f'<td style="padding:2px 0;">{html.escape(str(v))}</td></tr>'
                )

        return (
            f'<div class="hv-operation-panel" style="font-family:monospace;font-size:12px;'
            f'padding:8px;border-left:3px solid #b97a00;background:#fbf5f0;margin-bottom:6px;">'
            f'<div style="font-weight:bold;margin-bottom:4px;color:#8a5c00;">Operation Context</div>'
            f'<table style="border-collapse:collapse;">{rows}</table></div>'
        )

    def get_panel_specs(self, obj: Any) -> Optional[List[PanelSpec]]:
        html_panel = self.get_html_panel(obj)
        if html_panel is None:
            return None
        return [PanelSpec(title="OperationContext", html_content=html_panel, position="right", priority=400)]
